"AppConfig": {
  "startPage": string
  "menuItems": "MenuItem"
"AppConfig" -> "MenuItem"
  "footer": "FooterItem"
"AppConfig" -> "FooterItem"
  "ui": "UIConfig"
"AppConfig" -> "UIConfig"
  "publication": "PublicationInfos"
"AppConfig" -> "PublicationInfos"
}

"FooterItem": {
  "text": string
  "url": string
}

"MenuItem": {
  "label": string
  "link": string
}

"PublicationInfos": {
  "version": string
  "id": string
}

"UIConfig": {
  "theme": string
}
